cmake_minimum_required(VERSION 3.8)
project(video_reader)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_compile_options(-Wall -Wextra -Wpedantic)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(OpenCV REQUIRED COMPONENTS core videoio
  PATHS "/usr/lib/${CMAKE_LIBRARY_ARCHITECTURE}/cmake/opencv4"
  NO_DEFAULT_PATH)
find_package(cv_bridge REQUIRED)
add_executable(videor_reader src/video_reader.cpp)
ament_target_dependencies(videor_reader rclcpp sensor_msgs std_msgs cv_bridge)
target_include_directories(videor_reader PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(videor_reader ${OpenCV_LIBS})
install(TARGETS videor_reader DESTINATION lib/${PROJECT_NAME})
ament_package()
